// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcenpdfsstzgvvmcmymi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZW5wZGZzc3R6Z3Z2bWNteW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Mzc1MDcsImV4cCI6MjA3MjUxMzUwN30.9u1KEaHhaI9U4pt6ShLObXUnv8jOwkdePQmx5QyP0NM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});